from . import sale_order
from . import insurance_claim
from . import payment_type
from . import insurance_odoo_product_map
from . import payment_journal_mapping
from . import insurance_disease_code
from . import product_template
from . import insurance_config_settings
from . import stock_lot
from . import insurance_connect
from . import res_partner
from . import hib_config_settings
from . import res_company